/**
 * The universal exercise library — the seed every trainer starts with.
 *
 * Each trainer gets their own copy on signup (idempotent: re-running
 * skips exercises whose name already exists for that tenant). Trainers
 * can rename, archive, or override any of these freely without
 * affecting other trainers — they're just regular `exercises` rows
 * with the trainer's `tenant_id`.
 *
 * Set defaults match what `ExerciseForm` writes:
 *   - `default_rep_value.type = "sets" | "timed_sets"`
 *   - `default_rep_value.sets[i] = { reps?, seconds?, kg, rest, mode? }`
 *
 * Set overrides for a specific workout template or client session live
 * on `template_set_groups` / `session_set_groups` — those are
 * unaffected by changes here.
 *
 * Video URLs use YouTube SEARCH so they always resolve to current
 * tutorial content; trainers can paste a specific link of their
 * choice from the exercise edit page.
 */

export type UniversalSet =
  | { reps: number; mode: "reps" | "per_side" | "amrap" | "hold"; kg: number; rest: number }
  | { seconds: number; kg: number; rest: number };

export type UniversalExercise = {
  name: string;
  group: string;
  equipment: string | null;
  is_timed: boolean;
  default_rep_type: "fixed" | "range" | "unilateral" | "amrap" | "time";
  sets: UniversalSet[];
  default_rest_seconds: number;
};

function ytSearch(name: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " form tutorial")}`;
}

export function videoUrlFor(name: string): string {
  return ytSearch(name);
}

export const UNIVERSAL_GROUPS = [
  "lower body",
  "upper push",
  "upper pull",
  "olympic",
  "core",
  "carries",
  "conditioning",
  "mobility",
] as const;

export const UNIVERSAL_EXERCISES: UniversalExercise[] = [
  // ─── Lower body ────────────────────────────────────────────────────────
  {
    name: "Back squat",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 60, rest: 180 },
      { reps: 5, mode: "reps", kg: 60, rest: 180 },
      { reps: 5, mode: "reps", kg: 60, rest: 180 },
    ],
    default_rest_seconds: 180,
  },
  {
    name: "Front squat",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 50, rest: 150 },
      { reps: 5, mode: "reps", kg: 50, rest: 150 },
      { reps: 5, mode: "reps", kg: 50, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Goblet squat",
    group: "lower body",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 16, rest: 90 },
      { reps: 10, mode: "reps", kg: 16, rest: 90 },
      { reps: 10, mode: "reps", kg: 16, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Bulgarian split squat",
    group: "lower body",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 12, rest: 90 },
      { reps: 10, mode: "per_side", kg: 12, rest: 90 },
      { reps: 10, mode: "per_side", kg: 12, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Walking lunge",
    group: "lower body",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 12, mode: "per_side", kg: 12, rest: 90 },
      { reps: 12, mode: "per_side", kg: 12, rest: 90 },
      { reps: 12, mode: "per_side", kg: 12, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Conventional deadlift",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 80, rest: 180 },
      { reps: 5, mode: "reps", kg: 80, rest: 180 },
      { reps: 5, mode: "reps", kg: 80, rest: 180 },
    ],
    default_rest_seconds: 180,
  },
  {
    name: "Sumo deadlift",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 80, rest: 180 },
      { reps: 5, mode: "reps", kg: 80, rest: 180 },
      { reps: 5, mode: "reps", kg: 80, rest: 180 },
    ],
    default_rest_seconds: 180,
  },
  {
    name: "Romanian deadlift",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 60, rest: 120 },
      { reps: 8, mode: "reps", kg: 60, rest: 120 },
      { reps: 8, mode: "reps", kg: 60, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Hip thrust",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 60, rest: 120 },
      { reps: 8, mode: "reps", kg: 60, rest: 120 },
      { reps: 8, mode: "reps", kg: 60, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Glute bridge",
    group: "lower body",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 15, mode: "reps", kg: 0, rest: 60 },
      { reps: 15, mode: "reps", kg: 0, rest: 60 },
      { reps: 15, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Leg press",
    group: "lower body",
    equipment: "machine",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 100, rest: 90 },
      { reps: 10, mode: "reps", kg: 100, rest: 90 },
      { reps: 10, mode: "reps", kg: 100, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Leg curl",
    group: "lower body",
    equipment: "machine",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 30, rest: 60 },
      { reps: 12, mode: "reps", kg: 30, rest: 60 },
      { reps: 12, mode: "reps", kg: 30, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Leg extension",
    group: "lower body",
    equipment: "machine",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 30, rest: 60 },
      { reps: 12, mode: "reps", kg: 30, rest: 60 },
      { reps: 12, mode: "reps", kg: 30, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Standing calf raise",
    group: "lower body",
    equipment: "machine",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 15, mode: "reps", kg: 40, rest: 60 },
      { reps: 15, mode: "reps", kg: 40, rest: 60 },
      { reps: 15, mode: "reps", kg: 40, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Pistol squat",
    group: "lower body",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 5, mode: "per_side", kg: 0, rest: 90 },
      { reps: 5, mode: "per_side", kg: 0, rest: 90 },
      { reps: 5, mode: "per_side", kg: 0, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Air squat",
    group: "lower body",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 20, mode: "reps", kg: 0, rest: 45 },
      { reps: 20, mode: "reps", kg: 0, rest: 45 },
      { reps: 20, mode: "reps", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Box jump",
    group: "lower body",
    equipment: "box",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 0, rest: 60 },
      { reps: 8, mode: "reps", kg: 0, rest: 60 },
      { reps: 8, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Hack squat",
    group: "lower body",
    equipment: "machine",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 80, rest: 90 },
      { reps: 10, mode: "reps", kg: 80, rest: 90 },
      { reps: 10, mode: "reps", kg: 80, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Sled push",
    group: "lower body",
    equipment: "sled",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 30, kg: 60, rest: 60 },
      { seconds: 30, kg: 60, rest: 60 },
      { seconds: 30, kg: 60, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Step-up",
    group: "lower body",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 12, rest: 60 },
      { reps: 10, mode: "per_side", kg: 12, rest: 60 },
      { reps: 10, mode: "per_side", kg: 12, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Reverse lunge",
    group: "lower body",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 12, rest: 75 },
      { reps: 10, mode: "per_side", kg: 12, rest: 75 },
      { reps: 10, mode: "per_side", kg: 12, rest: 75 },
    ],
    default_rest_seconds: 75,
  },
  {
    name: "Single-leg RDL",
    group: "lower body",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 8, mode: "per_side", kg: 10, rest: 75 },
      { reps: 8, mode: "per_side", kg: 10, rest: 75 },
      { reps: 8, mode: "per_side", kg: 10, rest: 75 },
    ],
    default_rest_seconds: 75,
  },
  {
    name: "Nordic hamstring curl",
    group: "lower body",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 0, rest: 90 },
      { reps: 5, mode: "reps", kg: 0, rest: 90 },
      { reps: 5, mode: "reps", kg: 0, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Back extension",
    group: "lower body",
    equipment: "bench",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 0, rest: 60 },
      { reps: 12, mode: "reps", kg: 0, rest: 60 },
      { reps: 12, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Good morning",
    group: "lower body",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 30, rest: 90 },
      { reps: 8, mode: "reps", kg: 30, rest: 90 },
      { reps: 8, mode: "reps", kg: 30, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Trap bar deadlift",
    group: "lower body",
    equipment: "trap bar",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 70, rest: 150 },
      { reps: 5, mode: "reps", kg: 70, rest: 150 },
      { reps: 5, mode: "reps", kg: 70, rest: 150 },
    ],
    default_rest_seconds: 150,
  },

  // ─── Upper push ────────────────────────────────────────────────────────
  {
    name: "Bench press",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 50, rest: 150 },
      { reps: 5, mode: "reps", kg: 50, rest: 150 },
      { reps: 5, mode: "reps", kg: 50, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Incline bench press",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 40, rest: 120 },
      { reps: 8, mode: "reps", kg: 40, rest: 120 },
      { reps: 8, mode: "reps", kg: 40, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Dumbbell bench press",
    group: "upper push",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 20, rest: 90 },
      { reps: 10, mode: "reps", kg: 20, rest: 90 },
      { reps: 10, mode: "reps", kg: 20, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Overhead press",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 30, rest: 120 },
      { reps: 5, mode: "reps", kg: 30, rest: 120 },
      { reps: 5, mode: "reps", kg: 30, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Push press",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 35, rest: 120 },
      { reps: 5, mode: "reps", kg: 35, rest: 120 },
      { reps: 5, mode: "reps", kg: 35, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Push-up",
    group: "upper push",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 0, rest: 60 },
      { reps: 12, mode: "reps", kg: 0, rest: 60 },
      { reps: 12, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Dip",
    group: "upper push",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 0, rest: 90 },
      { reps: 8, mode: "reps", kg: 0, rest: 90 },
      { reps: 8, mode: "reps", kg: 0, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Lateral raise",
    group: "upper push",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 6, rest: 60 },
      { reps: 12, mode: "reps", kg: 6, rest: 60 },
      { reps: 12, mode: "reps", kg: 6, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Tricep pushdown",
    group: "upper push",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 20, rest: 60 },
      { reps: 12, mode: "reps", kg: 20, rest: 60 },
      { reps: 12, mode: "reps", kg: 20, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Skull crusher",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 20, rest: 60 },
      { reps: 10, mode: "reps", kg: 20, rest: 60 },
      { reps: 10, mode: "reps", kg: 20, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Handstand push-up",
    group: "upper push",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 0, rest: 120 },
      { reps: 5, mode: "reps", kg: 0, rest: 120 },
      { reps: 5, mode: "reps", kg: 0, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Close-grip bench press",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 40, rest: 120 },
      { reps: 8, mode: "reps", kg: 40, rest: 120 },
      { reps: 8, mode: "reps", kg: 40, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Arnold press",
    group: "upper push",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 12, rest: 90 },
      { reps: 10, mode: "reps", kg: 12, rest: 90 },
      { reps: 10, mode: "reps", kg: 12, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Landmine press",
    group: "upper push",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 20, rest: 75 },
      { reps: 10, mode: "per_side", kg: 20, rest: 75 },
      { reps: 10, mode: "per_side", kg: 20, rest: 75 },
    ],
    default_rest_seconds: 75,
  },
  {
    name: "Pec fly",
    group: "upper push",
    equipment: "machine",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 25, rest: 60 },
      { reps: 12, mode: "reps", kg: 25, rest: 60 },
      { reps: 12, mode: "reps", kg: 25, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Cable chest fly",
    group: "upper push",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 15, rest: 60 },
      { reps: 12, mode: "reps", kg: 15, rest: 60 },
      { reps: 12, mode: "reps", kg: 15, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Diamond push-up",
    group: "upper push",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },

  // ─── Upper pull ────────────────────────────────────────────────────────
  {
    name: "Pull-up",
    group: "upper pull",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 6, mode: "reps", kg: 0, rest: 120 },
      { reps: 6, mode: "reps", kg: 0, rest: 120 },
      { reps: 6, mode: "reps", kg: 0, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Chin-up",
    group: "upper pull",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 6, mode: "reps", kg: 0, rest: 120 },
      { reps: 6, mode: "reps", kg: 0, rest: 120 },
      { reps: 6, mode: "reps", kg: 0, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Lat pulldown",
    group: "upper pull",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 40, rest: 90 },
      { reps: 10, mode: "reps", kg: 40, rest: 90 },
      { reps: 10, mode: "reps", kg: 40, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Bent-over row",
    group: "upper pull",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 50, rest: 120 },
      { reps: 8, mode: "reps", kg: 50, rest: 120 },
      { reps: 8, mode: "reps", kg: 50, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Pendlay row",
    group: "upper pull",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 50, rest: 120 },
      { reps: 5, mode: "reps", kg: 50, rest: 120 },
      { reps: 5, mode: "reps", kg: 50, rest: 120 },
    ],
    default_rest_seconds: 120,
  },
  {
    name: "Seated cable row",
    group: "upper pull",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 35, rest: 90 },
      { reps: 10, mode: "reps", kg: 35, rest: 90 },
      { reps: 10, mode: "reps", kg: 35, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Single-arm dumbbell row",
    group: "upper pull",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 16, rest: 90 },
      { reps: 10, mode: "per_side", kg: 16, rest: 90 },
      { reps: 10, mode: "per_side", kg: 16, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Face pull",
    group: "upper pull",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 15, mode: "reps", kg: 15, rest: 60 },
      { reps: 15, mode: "reps", kg: 15, rest: 60 },
      { reps: 15, mode: "reps", kg: 15, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Barbell curl",
    group: "upper pull",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 20, rest: 60 },
      { reps: 10, mode: "reps", kg: 20, rest: 60 },
      { reps: 10, mode: "reps", kg: 20, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Hammer curl",
    group: "upper pull",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 10, rest: 60 },
      { reps: 10, mode: "reps", kg: 10, rest: 60 },
      { reps: 10, mode: "reps", kg: 10, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Muscle-up",
    group: "upper pull",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 3, mode: "reps", kg: 0, rest: 180 },
      { reps: 3, mode: "reps", kg: 0, rest: 180 },
      { reps: 3, mode: "reps", kg: 0, rest: 180 },
    ],
    default_rest_seconds: 180,
  },
  {
    name: "T-bar row",
    group: "upper pull",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 40, rest: 90 },
      { reps: 8, mode: "reps", kg: 40, rest: 90 },
      { reps: 8, mode: "reps", kg: 40, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Inverted row",
    group: "upper pull",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 0, rest: 75 },
      { reps: 10, mode: "reps", kg: 0, rest: 75 },
      { reps: 10, mode: "reps", kg: 0, rest: 75 },
    ],
    default_rest_seconds: 75,
  },
  {
    name: "Reverse fly",
    group: "upper pull",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 6, rest: 60 },
      { reps: 12, mode: "reps", kg: 6, rest: 60 },
      { reps: 12, mode: "reps", kg: 6, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Preacher curl",
    group: "upper pull",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 15, rest: 60 },
      { reps: 10, mode: "reps", kg: 15, rest: 60 },
      { reps: 10, mode: "reps", kg: 15, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Concentration curl",
    group: "upper pull",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 8, rest: 45 },
      { reps: 10, mode: "per_side", kg: 8, rest: 45 },
      { reps: 10, mode: "per_side", kg: 8, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Shrug",
    group: "upper pull",
    equipment: "dumbbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 20, rest: 60 },
      { reps: 12, mode: "reps", kg: 20, rest: 60 },
      { reps: 12, mode: "reps", kg: 20, rest: 60 },
    ],
    default_rest_seconds: 60,
  },

  // ─── Olympic ───────────────────────────────────────────────────────────
  {
    name: "Power clean",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 3, mode: "reps", kg: 50, rest: 150 },
      { reps: 3, mode: "reps", kg: 50, rest: 150 },
      { reps: 3, mode: "reps", kg: 50, rest: 150 },
      { reps: 3, mode: "reps", kg: 50, rest: 150 },
      { reps: 3, mode: "reps", kg: 50, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Hang clean",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 3, mode: "reps", kg: 45, rest: 150 },
      { reps: 3, mode: "reps", kg: 45, rest: 150 },
      { reps: 3, mode: "reps", kg: 45, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Power snatch",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 3, mode: "reps", kg: 35, rest: 150 },
      { reps: 3, mode: "reps", kg: 35, rest: 150 },
      { reps: 3, mode: "reps", kg: 35, rest: 150 },
      { reps: 3, mode: "reps", kg: 35, rest: 150 },
      { reps: 3, mode: "reps", kg: 35, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Clean and jerk",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 2, mode: "reps", kg: 50, rest: 180 },
      { reps: 2, mode: "reps", kg: 50, rest: 180 },
      { reps: 2, mode: "reps", kg: 50, rest: 180 },
      { reps: 2, mode: "reps", kg: 50, rest: 180 },
    ],
    default_rest_seconds: 180,
  },
  {
    name: "Thruster",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 30, rest: 90 },
      { reps: 8, mode: "reps", kg: 30, rest: 90 },
      { reps: 8, mode: "reps", kg: 30, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Wall ball",
    group: "olympic",
    equipment: "medicine ball",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 15, mode: "reps", kg: 9, rest: 60 },
      { reps: 15, mode: "reps", kg: 9, rest: 60 },
      { reps: 15, mode: "reps", kg: 9, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Kettlebell swing",
    group: "olympic",
    equipment: "kettlebell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 20, mode: "reps", kg: 16, rest: 60 },
      { reps: 20, mode: "reps", kg: 16, rest: 60 },
      { reps: 20, mode: "reps", kg: 16, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Turkish get-up",
    group: "olympic",
    equipment: "kettlebell",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 3, mode: "per_side", kg: 12, rest: 90 },
      { reps: 3, mode: "per_side", kg: 12, rest: 90 },
      { reps: 3, mode: "per_side", kg: 12, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Burpee",
    group: "olympic",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Push jerk",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 3, mode: "reps", kg: 40, rest: 150 },
      { reps: 3, mode: "reps", kg: 40, rest: 150 },
      { reps: 3, mode: "reps", kg: 40, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Split jerk",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 2, mode: "reps", kg: 45, rest: 180 },
      { reps: 2, mode: "reps", kg: 45, rest: 180 },
      { reps: 2, mode: "reps", kg: 45, rest: 180 },
    ],
    default_rest_seconds: 180,
  },
  {
    name: "Hang power snatch",
    group: "olympic",
    equipment: "barbell",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 3, mode: "reps", kg: 30, rest: 150 },
      { reps: 3, mode: "reps", kg: 30, rest: 150 },
      { reps: 3, mode: "reps", kg: 30, rest: 150 },
    ],
    default_rest_seconds: 150,
  },
  {
    name: "Box step-up to jump",
    group: "olympic",
    equipment: "box",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 6, mode: "per_side", kg: 0, rest: 75 },
      { reps: 6, mode: "per_side", kg: 0, rest: 75 },
      { reps: 6, mode: "per_side", kg: 0, rest: 75 },
    ],
    default_rest_seconds: 75,
  },

  // ─── Core ──────────────────────────────────────────────────────────────
  {
    name: "Plank",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 45, mode: "hold", kg: 0, rest: 45 },
      { reps: 45, mode: "hold", kg: 0, rest: 45 },
      { reps: 45, mode: "hold", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Side plank",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 30, mode: "hold", kg: 0, rest: 45 },
      { reps: 30, mode: "hold", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Hollow hold",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 30, mode: "hold", kg: 0, rest: 45 },
      { reps: 30, mode: "hold", kg: 0, rest: 45 },
      { reps: 30, mode: "hold", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Dead bug",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 0, rest: 45 },
      { reps: 10, mode: "reps", kg: 0, rest: 45 },
      { reps: 10, mode: "reps", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Bird dog",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 0, rest: 45 },
      { reps: 10, mode: "reps", kg: 0, rest: 45 },
      { reps: 10, mode: "reps", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Hanging leg raise",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
      { reps: 10, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Toes-to-bar",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 0, rest: 90 },
      { reps: 8, mode: "reps", kg: 0, rest: 90 },
      { reps: 8, mode: "reps", kg: 0, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Ab wheel rollout",
    group: "core",
    equipment: "ab wheel",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 8, mode: "reps", kg: 0, rest: 60 },
      { reps: 8, mode: "reps", kg: 0, rest: 60 },
      { reps: 8, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Russian twist",
    group: "core",
    equipment: "medicine ball",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 20, mode: "reps", kg: 5, rest: 45 },
      { reps: 20, mode: "reps", kg: 5, rest: 45 },
      { reps: 20, mode: "reps", kg: 5, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Pallof press",
    group: "core",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 10, mode: "per_side", kg: 12, rest: 45 },
      { reps: 10, mode: "per_side", kg: 12, rest: 45 },
      { reps: 10, mode: "per_side", kg: 12, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "V-up",
    group: "core",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 0, rest: 45 },
      { reps: 12, mode: "reps", kg: 0, rest: 45 },
      { reps: 12, mode: "reps", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Cable crunch",
    group: "core",
    equipment: "cable",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 12, mode: "reps", kg: 25, rest: 45 },
      { reps: 12, mode: "reps", kg: 25, rest: 45 },
      { reps: 12, mode: "reps", kg: 25, rest: 45 },
    ],
    default_rest_seconds: 45,
  },
  {
    name: "Mountain climber",
    group: "core",
    equipment: "bodyweight",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 30, kg: 0, rest: 30 },
      { seconds: 30, kg: 0, rest: 30 },
      { seconds: 30, kg: 0, rest: 30 },
    ],
    default_rest_seconds: 30,
  },

  // ─── Carries ───────────────────────────────────────────────────────────
  {
    name: "Farmer's carry",
    group: "carries",
    equipment: "dumbbell",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 40, kg: 24, rest: 60 },
      { seconds: 40, kg: 24, rest: 60 },
      { seconds: 40, kg: 24, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Suitcase carry",
    group: "carries",
    equipment: "kettlebell",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 40, kg: 20, rest: 60 },
      { seconds: 40, kg: 20, rest: 60 },
      { seconds: 40, kg: 20, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Overhead carry",
    group: "carries",
    equipment: "kettlebell",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 30, kg: 12, rest: 60 },
      { seconds: 30, kg: 12, rest: 60 },
      { seconds: 30, kg: 12, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Zercher carry",
    group: "carries",
    equipment: "barbell",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 30, kg: 30, rest: 60 },
      { seconds: 30, kg: 30, rest: 60 },
      { seconds: 30, kg: 30, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Sandbag carry",
    group: "carries",
    equipment: "sandbag",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 45, kg: 25, rest: 75 },
      { seconds: 45, kg: 25, rest: 75 },
      { seconds: 45, kg: 25, rest: 75 },
    ],
    default_rest_seconds: 75,
  },

  // ─── Conditioning ──────────────────────────────────────────────────────
  {
    name: "Row (erg)",
    group: "conditioning",
    equipment: "rower",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 600, kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Run",
    group: "conditioning",
    equipment: "none",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 1200, kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Bike (erg)",
    group: "conditioning",
    equipment: "bike",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 600, kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Assault bike",
    group: "conditioning",
    equipment: "assault bike",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 300, kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Jump rope",
    group: "conditioning",
    equipment: "rope",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 60, kg: 0, rest: 30 }, { seconds: 60, kg: 0, rest: 30 }, { seconds: 60, kg: 0, rest: 30 }],
    default_rest_seconds: 30,
  },
  {
    name: "Double under",
    group: "conditioning",
    equipment: "rope",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 30, mode: "reps", kg: 0, rest: 60 },
      { reps: 30, mode: "reps", kg: 0, rest: 60 },
      { reps: 30, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Ski erg",
    group: "conditioning",
    equipment: "ski erg",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 600, kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Sprint",
    group: "conditioning",
    equipment: "none",
    is_timed: true,
    default_rep_type: "time",
    sets: [
      { seconds: 30, kg: 0, rest: 90 },
      { seconds: 30, kg: 0, rest: 90 },
      { seconds: 30, kg: 0, rest: 90 },
      { seconds: 30, kg: 0, rest: 90 },
    ],
    default_rest_seconds: 90,
  },
  {
    name: "Broad jump",
    group: "conditioning",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [
      { reps: 5, mode: "reps", kg: 0, rest: 60 },
      { reps: 5, mode: "reps", kg: 0, rest: 60 },
      { reps: 5, mode: "reps", kg: 0, rest: 60 },
    ],
    default_rest_seconds: 60,
  },
  {
    name: "Lateral bound",
    group: "conditioning",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 6, mode: "per_side", kg: 0, rest: 45 },
      { reps: 6, mode: "per_side", kg: 0, rest: 45 },
      { reps: 6, mode: "per_side", kg: 0, rest: 45 },
    ],
    default_rest_seconds: 45,
  },

  // ─── Mobility / warm-up ────────────────────────────────────────────────
  {
    name: "World's greatest stretch",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 5, mode: "per_side", kg: 0, rest: 0 },
      { reps: 5, mode: "per_side", kg: 0, rest: 0 },
    ],
    default_rest_seconds: 0,
  },
  {
    name: "Couch stretch",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 60, mode: "hold", kg: 0, rest: 0 },
      { reps: 60, mode: "hold", kg: 0, rest: 0 },
    ],
    default_rest_seconds: 0,
  },
  {
    name: "90/90 hip stretch",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 45, mode: "hold", kg: 0, rest: 0 },
      { reps: 45, mode: "hold", kg: 0, rest: 0 },
    ],
    default_rest_seconds: 0,
  },
  {
    name: "Pigeon pose",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 60, mode: "hold", kg: 0, rest: 0 },
      { reps: 60, mode: "hold", kg: 0, rest: 0 },
    ],
    default_rest_seconds: 0,
  },
  {
    name: "Hip CARs",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "unilateral",
    sets: [
      { reps: 5, mode: "per_side", kg: 0, rest: 0 },
      { reps: 5, mode: "per_side", kg: 0, rest: 0 },
    ],
    default_rest_seconds: 0,
  },
  {
    name: "Thoracic spine extension",
    group: "mobility",
    equipment: "foam roller",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [{ reps: 8, mode: "reps", kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Banded shoulder dislocate",
    group: "mobility",
    equipment: "band",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [{ reps: 10, mode: "reps", kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Foam roll quads",
    group: "mobility",
    equipment: "foam roller",
    is_timed: true,
    default_rep_type: "time",
    sets: [{ seconds: 60, kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Cat-cow",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [{ reps: 10, mode: "reps", kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
  {
    name: "Downward dog",
    group: "mobility",
    equipment: "bodyweight",
    is_timed: false,
    default_rep_type: "fixed",
    sets: [{ reps: 30, mode: "hold", kg: 0, rest: 0 }],
    default_rest_seconds: 0,
  },
];

/**
 * Convert a single universal entry into the JSONB shape that
 * `exercises.default_rep_value` expects — matches what `ExerciseForm`
 * writes out (`type: "sets" | "timed_sets"`, plus a `sets` array).
 */
export function toRepValue(ex: UniversalExercise): Record<string, unknown> {
  return {
    type: ex.is_timed ? "timed_sets" : "sets",
    sets: ex.sets,
  };
}
